services:
  backend:
    build:
      context: ../better_ceneo
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ../better_ceneo/env/.env
    depends_on:
      - backend_db
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ../better_ceneo:/app

  backend_db:
    image: postgres:14-alpine
    volumes:
      - backend_db_volume:/var/lib/postgresql/data
    env_file:
      - ../better_ceneo/env/.env
    ports:
      - 5432:5432


volumes:
  backend_db_volume:
