# Generated by Django 4.1 on 2022-09-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_id', models.CharField(max_length=100)),
            ],
        ),
    ]
