# Generated by Django 4.1 on 2022-09-23 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapEbookResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('web_bookstore', models.CharField(max_length=100)),
                ('web_author', models.CharField(max_length=100)),
                ('web_title', models.CharField(max_length=200)),
                ('web_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('web_url', models.URLField(blank=True, max_length=250, null=True)),
                ('web_image_url', models.URLField(blank=True, max_length=250, null=True)),
                ('created', models.TimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='FastTaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input_search', models.CharField(max_length=200)),
                ('created', models.TimeField(auto_now=True)),
                ('search_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailTaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input_search', models.CharField(max_length=200)),
                ('created', models.TimeField(auto_now=True)),
                ('user_price_alert', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user_email', models.EmailField(max_length=254)),
                ('email_send_status', models.BooleanField(default=True)),
                ('search_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
